# Generated by Django 4.1.7 on 2023-02-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
